#!/usr/bin/env python3
import json
from pathlib import Path


catalog_path = Path(__file__).parents[1] / "Stasis" / "L10n" / "Localizable.xcstrings"

translations = {
    "%lld%%": "%lld%%",
    "%lld°C": "%lld°C",
    "Adapter": "电源适配器",
    "Adapter control is not supported on this device.": "此设备不支持适配器控制。",
    "Adapter Power Metrics": "适配器功率数据",
    "Advanced": "高级",
    "Approve Stasis in System Settings → Login Items to continue.": "请前往“系统设置”→“登录项”允许 Stasis 后继续。",
    "Automatic discharge": "自动放电",
    "Automatically resume charging when the battery drops below the threshold relative to your charge limit.": "电量低于充电上限所设阈值时自动恢复充电。",
    "Battery": "电池",
    "Battery & Power Adapter": "电池与电源适配器",
    "Battery Health": "电池健康度",
    "Battery mode": "电池状态",
    "Battery Mode": "电池状态",
    "Battery Power Metrics": "电池功率数据",
    "Battery Reading": "电量读数",
    "Battery Calibration": "电池校准",
    "Battery Temperature": "电池温度",
    "Blinking Orange Fast": "橙色快速闪烁",
    "Blinking Orange Slow": "橙色缓慢闪烁",
    "Calculating...": "正在计算…",
    "Calibrate": "校准",
    "Calibration": "校准",
    "Calibration Ready": "可以开始校准",
    "Calibration: Charging to 100%": "校准：正在充至 100%",
    "Calibration: Discharging to 10%": "校准：正在放电至 10%",
    "Calibration: Holding at 100%": "校准：正在 100% 保持一小时",
    "Calibration: Recharging to 100%": "校准：正在重新充至 100%",
    "Calibration: Returning to charge limit": "校准：正在恢复充电上限",
    "Charge limit": "充电上限",
    "Charge Limit Override": "临时充满",
    "Charge Management": "充电管理",
    "Charge management is not supported on this device.": "此设备不支持充电管理。",
    "Charging": "正在充电",
    "Charging Settings": "充电管理",
    "Charging control is not supported on this device.": "此设备不支持充电控制。",
    "Charging Paused": "充电已暂停",
    "Charging Resumed": "充电已恢复",
    "Charging resumes at": "恢复充电电量",
    "Charging status changed": "充电状态变化",
    "Charging Tools": "充电工具",
    "Check Again": "重新检查",
    "Control when Stasis sends you notifications.": "设置 Stasis 发送通知的时机。",
    "Cycle count": "循环次数",
    "Cycle Count": "循环次数",
    "Dashboard": "仪表盘",
    "Disable all notifications": "关闭所有通知",
    "Disable sleep until charge limit": "达到充电上限前阻止睡眠",
    "Discharge": "放电",
    "Discharge the battery to your charge limit when plugged in above the target level.": "接通电源且电量高于目标时，将电池放电至设定上限。",
    "Discharging": "正在放电",
    "Display battery percentage next to or inside the menu bar icon.": "在菜单栏电池图标旁或图标内显示电量百分比。",
    "Enable heat protection": "启用高温保护",
    "Enable charge management in Settings to apply the limit.": "请先在设置中启用充电管理，充电上限才会生效。",
    "Enable sailing mode": "启用浮动模式",
    "Failed to install charging helper": "充电控制助手安装失败",
    "Force Discharge": "强制放电",
    "General": "通用",
    "General system and battery status information shown in the menu dropdown.": "设置菜单面板中显示的系统与电池状态信息。",
    "Green": "绿色",
    "Health": "健康度",
    "Heat Protection": "高温保护",
    "Hidden": "隐藏",
    "Inside icon": "图标内",
    "Launch at login": "登录时启动",
    "LED during heat protection": "高温保护时的指示灯",
    "Limit the maximum charge level to extend battery lifespan.": "限制最高充电电量，以延长电池寿命。",
    "Live Power": "实时功率",
    "MagSafe LED Control": "MagSafe 指示灯",
    "Monthly automatic calibration": "每月自动校准",
    "MagSafe LED control is not supported on this device.": "此设备不支持 MagSafe 指示灯控制。",
    "Manage charging": "管理充电",
    "Manage MagSafe LED": "管理 MagSafe 指示灯",
    "Menu Bar Icon": "菜单栏图标",
    "Next to icon": "图标旁",
    "Not Charging": "未在充电",
    "Notifications": "通知",
    "Off": "关闭",
    "Ok": "好",
    "Orange": "橙色",
    "Open Login Items": "打开登录项设置",
    "Pause charging when the battery temperature exceeds the threshold.": "电池温度超过设定值时暂停充电。",
    "Plugged In (Not Charging)": "已接通电源（未充电）",
    "Power": "功率",
    "Power Adapter": "电源适配器",
    "Power distribution diagram": "功率流向图",
    "Power source": "电源来源",
    "Power Source": "电源来源",
    "Prevent your Mac from sleeping while charging towards the charge limit. Sleep is re-enabled once the limit is reached or the adapter is disconnected.": "充电至上限期间阻止 Mac 睡眠；达到上限或断开适配器后恢复睡眠。",
    "Quit": "退出",
    "Sailing Mode": "浮动模式",
    "Settings": "设置",
    "Show battery state": "显示电池状态",
    "Show percentage": "显示电量百分比",
    "Sleep Prevention": "睡眠控制",
    "Startup": "启动",
    "Start Calibration Now": "立即开始校准",
    "Stop Calibration": "停止校准",
    "Stasis Settings": "Stasis 设置",
    "Status": "状态",
    "System Power": "系统功率",
    "Temperature": "温度",
    "Temperature limit": "温度上限",
    "Threshold below limit": "低于上限的回充差值",
    "Time Remaining": "剩余时间",
    "Time until discharge": "预计可用时间",
    "Top Up": "充满",
    "Unknown": "未知",
    "Uptime": "开机时长",
    "Use hardware percentage": "使用硬件电量百分比",
    "Use the raw battery percentage instead of the macOS calibrated value.": "使用电池硬件原始百分比，而非 macOS 校准后的数值。",
    "Visuals": "显示",
    "Automatic calibration runs once each month at the next opportunity while power is connected.": "启用后每月在接通电源的下一次可用时机自动执行。",
    "Charge to 100%, discharge to 10%, recharge to 100%, hold for one hour, then return to your limit.": "先充至 100%，放电至 10%，再充至 100% 并保持一小时，最后恢复到原充电上限。",
}

with catalog_path.open(encoding="utf-8") as catalog_file:
    catalog = json.load(catalog_file)

strings = catalog.setdefault("strings", {})
for key, value in translations.items():
    entry = strings.setdefault(key, {})
    localizations = entry.setdefault("localizations", {})
    localizations["zh-Hans"] = {
        "stringUnit": {
            "state": "translated",
            "value": value,
        }
    }

with catalog_path.open("w", encoding="utf-8") as catalog_file:
    json.dump(catalog, catalog_file, ensure_ascii=False, indent=2)
    catalog_file.write("\n")
